[package]
name = "async-hid"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"

[target."cfg(target_os = \"windows\")".dependencies]
futures-lite = "1"
flume = "0.10"
windows = { version = "0.48", features = [
    "Devices_Enumeration",
    "Devices_HumanInterfaceDevice",
    "Foundation",
    "Foundation_Collections",
    "Storage",
    "Storage_Streams",
    "Win32_System_WinRT"
]}

[target."cfg(target_os = \"linux\")".dependencies]
tokio = { version = "1", features = ["net", "rt"] }
udev = "0.7"
nix = { version = "0.26", features = ["fs"] }

[target."cfg(target_os = \"macos\")".dependencies]
core-foundation = "0.9"
io-kit-sys = "0.3"
mach2 = "0.4"

[dev-dependencies]
simple_logger = "4"
tokio = { version = "1", features = ["full"] }